
import { Word, ShopItem, Achievement, Sugia } from './types';

export const SCRIPT_URL = 'https://script.google.com/macros/s/AKfycbyVRPErIu7-rm-3goBKB_KMy_0GPONmfQhVrPu9gdZI5dVjO7tdiX2dALkHaDZk3M2r/exec';

export const ACHIEVEMENTS: Achievement[] = [
  { id: 'zurba', title: 'צורבא מרבנן', desc: 'צבירת רצף (Combo) של 10 פגיעות רצופות', icon: '🎓' },
  { id: 'sinai', title: 'סיני ועוקר הרים', desc: 'ניצחון בוס בלי לספוג אף פגיעה', icon: '⛰️' },
  { id: 'gamir', title: 'גמיר וסביר', desc: 'רכישת כל השדרוגים והסקינים בחנות', icon: '📚' }
];

export const SUGIOT: Sugia[] = [
  { id: 0, title: 'דף ב: נהרדעא', location: 'nehardea', description: 'זרימת הנהר - האויבים נעים בתנועה גלית.', requiredLevel: 1, modifier: 'wave' },
  { id: 1, title: 'דף ב. נהרדעא', location: 'nehardea', description: 'עומק הדיון - צפיפות אויבים גדולה יותר.', requiredLevel: 8, modifier: 'density' },
  { id: 2, title: 'דף ג: סורא', location: 'sura', description: 'אש התורה - היזהר מאותיות אש הנופלות מהשמיים.', requiredLevel: 15, modifier: 'hazards' },
  { id: 3, title: 'דף ג. סורא', location: 'sura', description: 'לחץ הקושיא - האויבים מאיצים לקראתך.', requiredLevel: 22, modifier: 'accelerate' },
  { id: 4, title: 'דף ד: פומבדיתא', location: 'pumbedita', description: 'חריפות פומבדיתא - מילים קטנות ומהירות במיוחד.', requiredLevel: 29, modifier: 'sharpness' },
  { id: 5, title: 'דף ד. פומבדיתא', location: 'pumbedita', description: 'סערת הרוח - רוח צדדית משפיעה על תנועת המטוס.', requiredLevel: 36, modifier: 'drift' },
  { id: 6, title: 'דף ה: מחוזא', location: 'mahoza', description: 'ספקות - האויבים מהבהבים ונעלמים מהעין.', requiredLevel: 43, modifier: 'blink' },
  { id: 7, title: 'דף ה. מחוזא', location: 'mahoza', description: 'תוהו ובוהו - מסלולי תנועה קופצניים ולא צפויים.', requiredLevel: 50, modifier: 'chaos' },
  { id: 8, title: 'דף ו: מתא מחסיא', location: 'matamehasia', description: 'עומקא דדינא - הראות מוגבלת רק לאזור המטוס.', requiredLevel: 57, modifier: 'darkness' },
  { id: 9, title: 'דף ו. מתא מחסיא', location: 'matamehasia', description: 'מערבולת - האויבים נמשכים למרכז המסך.', requiredLevel: 64, modifier: 'vortex' },
  { id: 10, title: 'דף ז: בירא דלוות', location: 'beiradelvat', description: 'סופת ברקים - רוחות חזקות ומכשולים רבים.', requiredLevel: 71, modifier: 'storm' },
  { id: 11, title: 'דף ז. בירא דלוות', location: 'beiradelvat', description: 'סיום המסכת - שילוב של כל האתגרים לקרב האחרון.', requiredLevel: 78, modifier: 'final' }
];

export const SHOP_ITEMS: ShopItem[] = [
  { id: 'skin_default', name: 'מטוס רגיל', type: 'skin', price: 0, desc: 'מטוס קרב סטנדרטי שיורה כדורי אנרגיה', icon: '✈️' },
  { id: 'skin_gold', name: 'אור החמה', type: 'skin', price: 800, desc: 'מטוס יוקרתי שיורה קרן אור שמש עוצמתית (דרוש צורבא מרבנן)', icon: '☀️', requiredAchievement: 'zurba' },
  { id: 'skin_butzina', name: 'בוצינא קדישא', type: 'skin', price: 1000, desc: 'מטוס מואר בצבע סגול שיורה קווי לייזר', icon: '🕯️' },
  { id: 'skin_torah', name: 'אש התורה', type: 'skin', price: 1500, desc: 'ספר תורה הפולט כדורי אש קדושה (דרוש סיני ועוקר הרים)', icon: '🕎', requiredAchievement: 'sinai' },
  { id: 'skin_choshen', name: 'חושן המשפט', type: 'skin', price: 2000, desc: 'מבנה עוצמתי שיורה קשתות חשמל', icon: '💎' },
  { id: 'upgrade_bomb', name: '+1 פצצת תיקו', type: 'consumable', price: 250, desc: 'מנקה את כל המסך מאויבים', icon: '💣' },
  { id: 'item_shield', name: '+1 מגן דוד', type: 'consumable', price: 300, desc: 'מגן מפני פגיעה אחת (לחץ S) - עד 3', icon: '🛡️' },
  { id: 'item_freeze', name: '+1 שיקוי הזמן', type: 'consumable', price: 400, desc: 'מאט את כל האויבים לזמן ממושך (לחץ T) - עד 3', icon: '⏳' }
];

export const DICTIONARY: Word[] = [
    // מסכת בבא קמא
    { aramaic: "תּוֹרָא", hebrew: "שור", cat: "bava_kamma" },
    { aramaic: "חֲמָרָא", hebrew: "חמור", cat: "bava_kamma" },
    { aramaic: "נוּרָא", hebrew: "אש", cat: "bava_kamma" },
    { aramaic: "בֵּירָא", hebrew: "בור", cat: "bava_kamma" },
    { aramaic: "כַּלְבָּא", hebrew: "כלב", cat: "bava_kamma" },
    { aramaic: "שׁוּנְרָא", hebrew: "חתול", cat: "bava_kamma" },
    { aramaic: "גַּבְרָא", hebrew: "איש", cat: "bava_kamma" },
    { aramaic: "אַרְעָא", hebrew: "קרקע", cat: "bava_kamma" },
    { aramaic: "גְּלִימָא", hebrew: "בגד", cat: "bava_kamma" },
    { aramaic: "זוּזֵי", hebrew: "כסף", cat: "bava_kamma" },
    { aramaic: "רַחֲמָנָא", hebrew: "התורה", cat: "bava_kamma" },
    { aramaic: "הֶזֵּיקָא", hebrew: "נזק", cat: "bava_kamma" },
    { aramaic: "פְּסֵידָא", hebrew: "הפסד", cat: "bava_kamma" },
    { aramaic: "שׁוּמָא", hebrew: "שמאות", cat: "bava_kamma" },
    { aramaic: "סָהֲדִי", hebrew: "עדים", cat: "bava_kamma" },
    { aramaic: "כְּפֵילָא", hebrew: "כפל", cat: "bava_kamma" },
    { aramaic: "קַרְנָא", hebrew: "הקרן", cat: "bava_kamma" },
    { aramaic: "שְׁבָחָא", hebrew: "השבח", cat: "bava_kamma" },
    { aramaic: "דִּינָא", hebrew: "משפט", cat: "bava_kamma" },
    { aramaic: "מָנָא", hebrew: "כלי", cat: "bava_kamma" },
    { aramaic: "תְּבַר", hebrew: "שבר", cat: "bava_kamma" },
    { aramaic: "שְׁקַל", hebrew: "לקח", cat: "bava_kamma" },
    { aramaic: "שְׁדָא", hebrew: "זרק", cat: "bava_kamma" },
    { aramaic: "נְפַל", hebrew: "נפל", cat: "bava_kamma" },
    { aramaic: "קָטַל", hebrew: "הרג", cat: "bava_kamma" },
    { aramaic: "זְבַן", hebrew: "קנה", cat: "bava_kamma" },
    { aramaic: "יְהַב", hebrew: "נתן", cat: "bava_kamma" },
    { aramaic: "אָתָא", hebrew: "בא", cat: "bava_kamma" },
    { aramaic: "חֲזָא", hebrew: "ראה", cat: "bava_kamma" },
    { aramaic: "בְּעָה", hebrew: "שאל", cat: "bava_kamma" },
    { aramaic: "הָכָא", hebrew: "כאן", cat: "bava_kamma" },
    { aramaic: "הָתָם", hebrew: "שם", cat: "bava_kamma" },
    { aramaic: "הֵיכִי", hebrew: "איך", cat: "bava_kamma" },
    { aramaic: "הֵיכָא", hebrew: "איפה", cat: "bava_kamma" },
    { aramaic: "דִּילְמָא", hebrew: "אולי", cat: "bava_kamma" },
    { aramaic: "אִי", hebrew: "אם", cat: "bava_kamma" },
    { aramaic: "מַאי", hebrew: "מה", cat: "bava_kamma" },
    { aramaic: "תּוּ", hebrew: "עוד", cat: "bava_kamma" },
    { aramaic: "בָּעֵי", hebrew: "צריך", cat: "bava_kamma" },
    { aramaic: "תֵּיקוּ", hebrew: "תעמוד", cat: "bava_kamma" },

    // מסכת ברכות
    { aramaic: "אַבְדֵּיל", hebrew: "הבדיל", cat: "berachot" },
    { aramaic: "אַגְבָּא", hebrew: "הגב", cat: "berachot" },
    { aramaic: "אַדְּרַבָּה", hebrew: "להפך", cat: "berachot" },
    { aramaic: "אוֹרְחָא", hebrew: "דרך", cat: "berachot" },
    { aramaic: "אוּרְתָּא", hebrew: "ערב", cat: "berachot" },
    { aramaic: "אָזֵיל", hebrew: "הולך", cat: "berachot" },
    { aramaic: "אָזְלָא", hebrew: "הולכת", cat: "berachot" },
    { aramaic: "אַטּוּ", hebrew: "וכי?", cat: "berachot" },
    { aramaic: "אִי", hebrew: "אם", cat: "berachot" },
    { aramaic: "אִי בָּעֵית אֵימָא", hebrew: "אם תרצה אמור", cat: "berachot" },
    { aramaic: "אִיבַּעְיָא לְהוּ", hebrew: "נשאלה להם", cat: "berachot" },
    { aramaic: "אִיכָּא", hebrew: "יש", cat: "berachot" },
    { aramaic: "אִינִי?", hebrew: "האמנם?", cat: "berachot" },
    { aramaic: "אִינָשֵׁי", hebrew: "אנשים", cat: "berachot" },
    { aramaic: "אִיקְּלַע", hebrew: "נזדמן", cat: "berachot" },
    { aramaic: "אִיתְּמַר", hebrew: "נאמר", cat: "berachot" },
    { aramaic: "אֶלָּא", hebrew: "אלא", cat: "berachot" },
    { aramaic: "אֲמַר לֵיהּ", hebrew: "אמר לו", cat: "berachot" },
    { aramaic: "אֲנַן", hebrew: "אנחנו", cat: "berachot" },
    { aramaic: "אַסְמְכִינְהוּ", hebrew: "הסמיכום", cat: "berachot" },
    { aramaic: "אַפֵּי", hebrew: "פנים", cat: "berachot" },
    { aramaic: "אַשְׁכְּחֵיהּ", hebrew: "מצא אותו", cat: "berachot" },
    { aramaic: "אֲתָא", hebrew: "בא", cat: "berachot" },
    { aramaic: "אַתְיָא", hebrew: "באה", cat: "berachot" },
    { aramaic: "בָּדוּחַ", hebrew: "שמח", cat: "berachot" },
    { aramaic: "בַּהֲדֵי", hebrew: "יחד עם", cat: "berachot" },
    { aramaic: "בַּהֲדֵי הֲדָדֵי", hebrew: "ביחד", cat: "berachot" },
    { aramaic: "בְּדֵילְנָא", hebrew: "הפסקתי", cat: "berachot" },
    { aramaic: "בְּדַלְתְּ", hebrew: "הפסקת", cat: "berachot" },
    { aramaic: "בִּשְׁלָמָא", hebrew: "בשלום", cat: "berachot" },
    { aramaic: "בָּעֵי", hebrew: "שאל/ביקש", cat: "berachot" },
    { aramaic: "בָּר", hebrew: "בן", cat: "berachot" },
    { aramaic: "בְּרֵיהּ", hebrew: "בנו של", cat: "berachot" },
    { aramaic: "בָּצִיר", hebrew: "פחות", cat: "berachot" },
    { aramaic: "בָּתְרָךְ", hebrew: "אחריך", cat: "berachot" },
    { aramaic: "גַּבְרָא", hebrew: "איש", cat: "berachot" },
    { aramaic: "דַּיְקָא", hebrew: "מדויק", cat: "berachot" },
    { aramaic: "דִּילְמָא", hebrew: "שמא", cat: "berachot" },
    { aramaic: "דָּמֵי", hebrew: "דומה", cat: "berachot" },
    { aramaic: "הַאי", hebrew: "זה", cat: "berachot" },
    { aramaic: "הָכָא", hebrew: "כאן", cat: "berachot" },
    { aramaic: "הָכִי", hebrew: "כך", cat: "berachot" },
    { aramaic: "הָדַר", hebrew: "חזר", cat: "berachot" },
    { aramaic: "הָדְרָא", hebrew: "חוזרת", cat: "berachot" },
    { aramaic: "הוֹאִיל", hebrew: "כיוון", cat: "berachot" },
    { aramaic: "הִלּוּלָא", hebrew: "חתונה", cat: "berachot" },
    { aramaic: "הִלְכְתָא", hebrew: "הלכה", cat: "berachot" },
    { aramaic: "הַיְינוּ", hebrew: "זהו", cat: "berachot" },
    { aramaic: "הָנֵי", hebrew: "אלו", cat: "berachot" },
    { aramaic: "הַשְׁתָּא", hebrew: "עכשיו", cat: "berachot" },
    { aramaic: "הָתָם", hebrew: "שם", cat: "berachot" },
    { aramaic: "וְתוּ לָא", hebrew: "ויותר לא", cat: "berachot" },
    { aramaic: "זִימְנָא", hebrew: "פעם", cat: "berachot" },
    { aramaic: "חֲזָא", hebrew: "ראה", cat: "berachot" },
    { aramaic: "חֲמָרָא", hebrew: "חמור", cat: "berachot" },
    { aramaic: "חָלְפִי", hebrew: "עוברים", cat: "berachot" },
    { aramaic: "טוּבָא", hebrew: "הרבה", cat: "berachot" },
    { aramaic: "טָעוּתָא", hebrew: "טעות", cat: "berachot" },
    { aramaic: "טְפֵי", hebrew: "יותר", cat: "berachot" },
    { aramaic: "יָהֲבִי", hebrew: "נותנים", cat: "berachot" },
    { aramaic: "יַתִּירָא", hebrew: "מיותר", cat: "berachot" },
    { aramaic: "יְמָמָא", hebrew: "יום", cat: "berachot" },
    { aramaic: "יָתֵיב", hebrew: "יושב", cat: "berachot" },
    { aramaic: "כּוּלֵּי עָלְמָא", hebrew: "כל העולם", cat: "berachot" },
    { aramaic: "כִּי", hebrew: "כאשר", cat: "berachot" },
    { aramaic: "כְּמַאן", hebrew: "כמי", cat: "berachot" },
    { aramaic: "כְּמָר", hebrew: "כחכם", cat: "berachot" },
    { aramaic: "כְּווֹתֵיהּ", hebrew: "כמותו", cat: "berachot" },
    { aramaic: "לָאו", hebrew: "לא", cat: "berachot" },
    { aramaic: "לֵיהּ", hebrew: "לו", cat: "berachot" },
    { aramaic: "לֵיכָּא", hebrew: "אין", cat: "berachot" },
    { aramaic: "לֵילְיָא", hebrew: "לילה", cat: "berachot" },
    { aramaic: "לְמֵימְרָא", hebrew: "לומר", cat: "berachot" },
    { aramaic: "לְעוֹלָם", hebrew: "באמת", cat: "berachot" },
    { aramaic: "מַאי", hebrew: "מה", cat: "berachot" },
    { aramaic: "מַאי מַשְׁמַע", hebrew: "מה המשמעות", cat: "berachot" },
    { aramaic: "מַאן", hebrew: "מי", cat: "berachot" },
    { aramaic: "מַהוּ", hebrew: "מה הדין", cat: "berachot" },
    { aramaic: "מַהְדְּרִינַן", hebrew: "מחזירים אנו", cat: "berachot" },
    { aramaic: "מִידִי", hebrew: "דבר", cat: "berachot" },
    { aramaic: "וְלָא מִידֵּי", hebrew: "ולא כלום", cat: "berachot" },
    { aramaic: "מִיהָא", hebrew: "בכל אופן", cat: "berachot" },
    { aramaic: "מֵיתִיבִי", hebrew: "משיבים (קושיה)", cat: "berachot" },
    { aramaic: "מִכְּדִי", hebrew: "הרי", cat: "berachot" },
    { aramaic: "מְצַלֵּי", hebrew: "מתפלל", cat: "berachot" },
    { aramaic: "מָר", hebrew: "אדון", cat: "berachot" },
    { aramaic: "מַשְׁכַּחַתְּ", hebrew: "מוצא", cat: "berachot" },
    { aramaic: "מַטְרְחִינַן", hebrew: "מטריחים אנו", cat: "berachot" },
    { aramaic: "נַמִי", hebrew: "גם", cat: "berachot" },
    { aramaic: "נָפֵיק", hebrew: "יוצא", cat: "berachot" },
    { aramaic: "נֶחְזֵי", hebrew: "נראה", cat: "berachot" },
    { aramaic: "נֵימָא", hebrew: "נאמר", cat: "berachot" },
    { aramaic: "סְבִירָא לֵיהּ", hebrew: "סובר", cat: "berachot" },
    { aramaic: "סֵיפָא", hebrew: "סוף", cat: "berachot" },
    { aramaic: "עֲבַד", hebrew: "עשה", cat: "berachot" },
    { aramaic: "עָבֵיד", hebrew: "עשה", cat: "berachot" },
    { aramaic: "עִידָּנָא", hebrew: "זמן", cat: "berachot" },
    { aramaic: "עָיֵיל", hebrew: "ונכנס", cat: "berachot" },
    { aramaic: "פַּלְגָא", hebrew: "חצי", cat: "berachot" },
    { aramaic: "פַּסְקֵיהּ", hebrew: "הפסיקו", cat: "berachot" },
    { aramaic: "פְּשִׁיטָא", hebrew: "פשוט", cat: "berachot" },
    { aramaic: "צַפְרָא", hebrew: "בוקר", cat: "berachot" },
    { aramaic: "צְלוֹתָא", hebrew: "תפילה", cat: "berachot" },
    { aramaic: "קָאֵי", hebrew: "עומד", cat: "berachot" },
    { aramaic: "קַמָּא", hebrew: "ראשון", cat: "berachot" },
    { aramaic: "קַמַּיְיתָא", hebrew: "ראשונה", cat: "berachot" },
    { aramaic: "רַחֲמֵי", hebrew: "רחמים", cat: "berachot" },
    { aramaic: "רֵישָׁא", hebrew: "ראש", cat: "berachot" },
    { aramaic: "וּרְמִינְהוּ", hebrew: "והשליכו (סתירה)", cat: "berachot" },
    { aramaic: "שָׁאנֵי", hebrew: "שונה", cat: "berachot" },
    { aramaic: "שְׁמַע מִינַּהּ", hebrew: "למד ממנה", cat: "berachot" },
    { aramaic: "שְׁרָא", hebrew: "התיר", cat: "berachot" },
    { aramaic: "תַּנְיָא", hebrew: "שנויה בברייתא", cat: "berachot" },
    { aramaic: "תְּנֵינָא", hebrew: "שנינו", cat: "berachot" },
    { aramaic: "תָּא שְׁמַע", hebrew: "בוא שמע", cat: "berachot" },
    { aramaic: "תְּלָת", hebrew: "שלוש", cat: "berachot" },
    { aramaic: "תַּקְּנַהּ", hebrew: "תיקנה", cat: "berachot" },

    // מילים נפוצות
    { aramaic: "אַדְּרַבָּה", hebrew: "להפך", cat: "common" },
    { aramaic: "אִדַּך", hebrew: "האחר", cat: "common" },
    { aramaic: "אוֹשְׁפִּיזָא", hebrew: "אכסניה", cat: "common" },
    { aramaic: "אִידֵּי", hebrew: "זה", cat: "common" },
    { aramaic: "אֵימַת", hebrew: "מתי", cat: "common" },
    { aramaic: "אֵימָא", hebrew: "אמור", cat: "common" },
    { aramaic: "אִית", hebrew: "יש", cat: "common" },
    { aramaic: "אִיתְּמַר", hebrew: "נאמר", cat: "common" },
    { aramaic: "אַכַּתִּי", hebrew: "עדיין", cat: "common" },
    { aramaic: "אֲנָא", hebrew: "אני", cat: "common" },
    { aramaic: "אַתְרָא", hebrew: "מקום", cat: "common" },
    { aramaic: "בֵּי", hebrew: "בית", cat: "common" },
    { aramaic: "בָּתַר", hebrew: "אחרי", cat: "common" },
    { aramaic: "גַּוְונָא", hebrew: "אופן", cat: "common" },
    { aramaic: "גִּירְסָא", hebrew: "לימוד", cat: "common" },
    { aramaic: "דַּוְקָא", hebrew: "בדיוק", cat: "common" },
    { aramaic: "הָא", hebrew: "הרי", cat: "common" },
    { aramaic: "הֲוָה", hebrew: "היה", cat: "common" },
    { aramaic: "הֵי", hebrew: "איזה", cat: "common" },
    { aramaic: "זִיל", hebrew: "לך", cat: "common" },
    { aramaic: "זְבַן", hebrew: "קנה", cat: "common" },
    { aramaic: "חַד", hebrew: "אחד", cat: "common" },
    { aramaic: "טַעְמָא", hebrew: "הטעם", cat: "common" },
    { aramaic: "יָכִיל", hebrew: "יכול", cat: "common" },
    { aramaic: "לְגַמְרֵי", hebrew: "לחלוטין", cat: "common" },
    { aramaic: "לְהוּ", hebrew: "להם", cat: "common" },
    { aramaic: "לְמֵימְרָא", hebrew: "לומר", cat: "common" },
    { aramaic: "לֵית", hebrew: "אין", cat: "common" },
    { aramaic: "מָגֵן", hebrew: "חינם", cat: "common" },
    { aramaic: "מְהַנֵי", hebrew: "מועיל", cat: "common" },
    { aramaic: "מָטוּ", hebrew: "הגיעו", cat: "common" },
    { aramaic: "מִסְתַּפְּינָא", hebrew: "אני מפחד", cat: "common" },
    { aramaic: "מְצַעַר", hebrew: "מצטער", cat: "common" },
    { aramaic: "מִקַּמֵּי", hebrew: "מלפני", cat: "common" },
    { aramaic: "מְשַׁנֵּי", hebrew: "מתרץ", cat: "common" },
    { aramaic: "נִיחָא", hebrew: "נוח", cat: "common" },
    { aramaic: "נֵימָא", hebrew: "נאמר", cat: "common" },
    { aramaic: "נָפֵיק", hebrew: "יוצא", cat: "common" },
    { aramaic: "נָקֵיט", hebrew: "מחזיק", cat: "common" },
    { aramaic: "סָבַר", hebrew: "חשב", cat: "common" },
    { aramaic: "סַגִּי", hebrew: "מספיק", cat: "common" },
    { aramaic: "סַיֵּים", hebrew: "סיים", cat: "common" },
    { aramaic: "עֲבַד", hebrew: "עשה", cat: "common" },
    { aramaic: "עַל", hebrew: "נכנס", cat: "common" },
    { aramaic: "עָיֵיל", hebrew: "נכנס", cat: "common" },
    { aramaic: "עָלְמָא", hebrew: "עולם", cat: "common" },
    { aramaic: "פְּלוֹנִי", hebrew: "אלמוני", cat: "common" },
    { aramaic: "פָּלֵיג", hebrew: "חולק", cat: "common" },
    { aramaic: "פִּרְקָא", hebrew: "דרשה", cat: "common" },
    { aramaic: "קָא", hebrew: "זה", cat: "common" },
    { aramaic: "קָטִיל", hebrew: "הורג", cat: "common" },
    { aramaic: "קַמָּא", hebrew: "ראשון", cat: "common" },
    { aramaic: "רְמָא", hebrew: "הטיל", cat: "common" },
    { aramaic: "שַׁוְּיֵיהּ", hebrew: "עשה אותו", cat: "common" },
    { aramaic: "שַׁיְילֵיהּ", hebrew: "שאל אותו", cat: "common" },
    { aramaic: "שְׁכִיחַ", hebrew: "מצוי", cat: "common" },
    { aramaic: "שַׁפִּיר", hebrew: "יפה", cat: "common" },
    { aramaic: "שָׁקֵיל", hebrew: "לוקח", cat: "common" },
    { aramaic: "תְּהֵא", hebrew: "תהיה", cat: "common" },
    { aramaic: "תְּיוּבְתָּא", hebrew: "קושיה", cat: "common" },
    { aramaic: "תַּלְיָא", hebrew: "תלוי", cat: "common" },
    { aramaic: "תְּנָא", hebrew: "שנה", cat: "common" },
    { aramaic: "תְּרֵי", hebrew: "שניים", cat: "common" }
];
